- name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: padavan-ng_${{ env.CONFIG_VENDOR }}_${{ env.CONFIG_FIRMWARE_PRODUCT_ID }}_${{ env.BUILD_TIMESTAMP }}
          retention-days: 7
          path: |
            ${{ env.FW_FILE_NAME }}
            build.config

      - name: Check firmware size
        run: |
          partitions=padavan-ng/trunk/configs/boards/$CONFIG_VENDOR/$CONFIG_FIRMWARE_PRODUCT_ID/partitions.config
          [[ -f "$partitions" ]] || { echo "Partitions config not found"; exit 1; }
          max_fw_size="$(awk '/Firmware/ { getline; getline; sub(",", ""); print strtonum($2); }' "$partitions")"
          fw_size="$(stat -c %s "$FW_FILE_NAME")"
          if (( fw_size > max_fw_size )); then
            fw_size_fmtd="$(numfmt --grouping "$fw_size") bytes"
            max_fw_size_fmtd="$(numfmt --grouping "$max_fw_size") bytes"
            echo "Firmware size ($fw_size_fmtd) exceeds max size ($max_fw_size_fmtd) for your target device"
            exit 1
          fi
